<?php

$PROJECT_FOLDER = "/agnes";
$TICKETS_PACKAGE_FOLDER = "/tickets";

$PROJECT_ROOT_DIR = $_SERVER['DOCUMENT_ROOT'] . $PROJECT_FOLDER;
$TICKETS_PACKAGE_DIR = $PROJECT_ROOT_DIR . $TICKETS_PACKAGE_FOLDER;